name: Push to NuGet

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Build & Package", "Release Build & Package"]
    types:
      - completed

jobs:
  deployment:
    runs-on: windows-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: Download Artifacts
      uses: actions/download-artifact@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Push to NuGet
      run: dotnet nuget push ./nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  on-failure:
    runs-on: windows-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - run: echo 'The triggering workflow failed. Publishing NuGet packages not required.'